const T = {
uz:{
  nav_ind:"Ko'rsatkichlar",nav_lots:"Lotlar",nav_price:"Narxlar",nav_about:"Biz haqimizda",nav_contacts:"Kontaktlar",
    nav_faq:"Savol-Javob",
  faq_tag:"Asosiy savollarga javoblar",faq_title:"Loyiha haqida",
  faq_lead:"O'zbekiston Respublikasi Vazirlar Mahkamasi qarorlari asosida tayyorlangan javoblar.",
  faq1_t:"Hududni tozalash qiymati va muddati",faq1_d:"Hududni tozalash va tayyorlash bo'yicha umumiy xarajatlar <strong>$145.7 mln</strong>. Muddati — 9–12 oy.",faq1_l:"Huquqiy asos: VMQ №414 — 10 iyul 2024 yil",
  faq2_t:"Investor xarajatlarini qoplash",faq2_d:"Avanslanган xarajatlarni qoplash keyingi muzokaralar bosqichida alohida qarz shartnomasi orqali tartibga solinadi.",faq2_l:"Huquqiy asos: VMQ №461 — 5 iyun 2019 yil (30-band)",
  faq3_t:"Qirg'oq parki va loyiha chegaralari",faq3_d:"Qirg'oq zonasi to'liq loyiha chegaralariga kiritilgan. Bozsuv kanali bo'ylab yashil alleya.",faq3_l:"Huquqiy asos: VMQ №414 — Bozsuv kanali va Foziltepa ko'chasi",
  faq4_t:"Yer foydalanish koeffitsienti (FAR)",faq4_d:"<strong>FAR = 4</strong>, o'rtacha 33 qavat, umumiy qurilish maydoni <strong>1.1 mln m²</strong>.",faq4_l:"Huquqiy asos: VMQ №83 — 28 fevral 2026 yil",
  faq5_t:"Loyiha hududining tarkibi",faq5_note:"* Master-plan ROX Group kompaniyasi tomonidan ishlab chiqilgan",
  ft1:"Umumiy maydon",ft2:"Qurilish maydoni",ft3:"Kompensatsiya va qulash",ft4:"Sog'liqni saqlash uchun avtoturargoh",ft5:"Yashil zonalar va yo'llar",ft5v:"Aniqlanmoqda",ft6:"Umumiy kompensatsiya summasi",
    nav_fut:"Kelajak",
  fut_tag:"Uchtepa City — Kelajak",fut_title:"Loyihaning kelajagi",fut_lead:"Uchtepa City qanday ko'rinishda bo'lishini tasavvur qiling — video va vizualizatsiyalar orqali.",
  t1t:"Kompaniya tashkil etildi",t1d:"2018 yilda Olmazor Business City loyihasi bilan faoliyatimiz boshlandi.",
    nav_proj:"Loyihalar",
  proj_tag:"Amalga oshirilgan loyihalar",proj_title:"Bizning tajribamiz",
  proj_lead:"Uchtepa City qurilishidan oldin biz Toshkentning eng yirik rekonstruksiya loyihalarini muvaffaqiyatli amalga oshirdik.",
  proj1_tag:"Tugallangan · 2022",proj1_desc:"23 gektar maydonida eski va buzilgan binolar qulandi. O'rniga zamonaviy biznes markazi va turar-joy majmuasi qurildi.",
  proj2_tag:"Tugallangan · 2023",proj2_desc:"44.5 gektar — Toshkentdagi eng yirik rekonstruksiya loyihalaridan biri. Eski mahalla to'liq yangilandi.",
  lbl_before:"Oldin",lbl_after:"Keyin",
  hero_tag:"Investitsiya loyihasi • Toshkent, Uchtepa tumani",
  hero_desc:"26 gektar maydonida zamonaviy shahar — 31 ta turar-joy binosi, 2 ta biznes markaz, maktab, MTM va Bozsuv kanali bo'ylab yashil alleya.",
  hero_btn:"Ko'rsatkichlarni ko'rish",
  kpi1:"Qurilish maydoni",kpi2:"Kompensatsiya",kpi3:"Loyiha hududi",
  ind_tag:"Umumiy texnik-iqtisodiy ko'rsatkichlar",ind_title:"Loyiha ko'rsatkichlari",
  ind_lead:"Uchtepa City master-plani asosida hisoblangan texnik-iqtisodiy ko'rsatkichlar.",
  i1:"Lotlar hududi umumiy maydoni",i2:"Umumiy qurilish maydoni",i3:"Umumiy yashil maydon",
  i4:"Biznes markazlari soni",i5:"Biznes markazlari maydoni",i6:"Turar-joy binolari soni",
  i7:"Turar-joy qavatlar soni",i8:"Turar-joy umumiy qavatlar maydoni",i9:"Umumiy xonadonlar soni",
  i10:"Aholi soni",i11:"Maktab qurilish maydoni",i12:"Maktab qavatlar soni",
  i13:"Maktab qavatlar umumiy maydoni",i14:"MTM qurilish maydoni",i15:"MTM qavatlar soni",
  i16:"MTM qavatlar maydoni",i17:"Yer usti avtoturargoh o'rinlari",
  i18:"Savdo sotiq qavatlar umumiy maydoni",i19:"Yer osti avtoturargoh o'rinlari",
  plan_cap:"Uchtepa City — Umumiy bosh reja",
  lots_tag:"Hududning lotlarga bo'linishi",lots_title:"15 ta alohida lot",
  lots_lead:"Umumiy maydon 19.4 Ga. Har bir lot alohida mulk sifatida ro'yxatdan o'tkazilishi mumkin.",
  th_n:"Lot",th_type:"Tur",th_area:"Maydon",
  b_res:"Turar-joy",b_biz:"Biznes markaz",b_soc:"Maktab",b_mtm:"Bog'cha (MTM)",b_park:"Avtoturargoh",
  func_tag:"Binolarning funksional taqsimlashi",func_title:"Funksional zonalar",
  leg1_t:"Turar-joy binolari",leg1_d:"31 ta bino, 18–22 qavat. Umumiy qavatlar maydoni 819 809.6 m². 6 664 ta xonadon, 22 148 ta aholi.",
  leg2_t:"Biznes markazlari",leg2_d:"2 ta biznes markaz. Umumiy maydoni 246 328.8 m². Ofis, savdo va xizmat ko'rsatish zonalari.",
  leg3_t:"Maktab binosi",leg3_d:"4 qavatli maktab. Qurilish maydoni 1 719.3 m², umumiy qavatlar maydoni 6 877.2 m².",
  leg4_t:"MTM binosi (Bog'cha)",leg4_d:"2 qavatli MTM. Qurilish maydoni 951.5 m², umumiy qavatlar maydoni 1 903 m².",
  price_tag:"Narxlar",price_title:"Investitsiya qiymati",
  price_lead:"Raqobatbardosh narxlar va moslashuvchan to'lov shartlari bilan investorlar uchun eng qulay sharoitlar.",
  p1_type:"Butun loyiha",p1_neg:"Kelishiladi",p1_desc:"Barcha 15 ta lot va infratuzilma bilan birga 19.4 ga yer uchastkasining to'liq narxi.",
  p2_type:"1 m² narxi (o'rtacha)",p2_neg:"Kelishiladi",p2_desc:"Lotning joylashuvi va maqsadiga qarab kvadrat metr narxi. Aniq narx har bir lot uchun alohida kelishiladi.",
  p3_type:"Minimal lot (№4)",p3_neg:"Kelishiladi",p3_desc:"Eng kichik lot — №4 (5 871.2 m², Turar-joy binosi). Kichik va o'rta investorlar uchun qulay kirish nuqtasi.",
  p_req:"So'rov yuborish →",p_ask:"Lot narxini so'rash →",p_info:"Batafsil ma'lumot →",
  comp_title:"Qo'shni developerlarning o'rtacha narxi (m² / $)",our_price:"Bizning narx",our_val:"Kelishiladi",
  about_tag:"Biz haqimizda",about_title:"Bizning tarix",
  ab1:"<strong>Uchtepa City</strong> — bu faqat qurilish loyihasi emas. Bu yillar davomida Toshkentning shahar muhitini o'zgartirish bo'yicha tajriba to'plagan jamoa natijasidir.",
  ab2:"Kompaniyamiz ixtisoslashgan qurilish va rekonstruksiya sohasida faoliyat yuritib, eski va buzilgan uy-joylarni qulash hamda yangi zamonaviy binolar qurish bo'yicha katta tajribaga ega.",
  ab3:"Har bir loyihada biz qurilish sifatiga, ekologik me'yorlarga va mahalliy aholi manfaatlariga alohida e'tibor beramiz. <strong>Uchtepa City</strong> — bizning eng yirik va eng obro'li loyihamiz.",
  t1t:"Kompaniya tashkil etildi",t1d:"Toshkent shahrida qurilish va qayta qurish bo'yicha ixtisoslashgan firma ochildi.",
  t2t:"Birinchi yirik loyiha",t2d:"Yunusobod tumanida eski uy-joylar qulandi, o'rniga zamonaviy ko'p qavatli binolar qurildi.",
  t3t:"Mirzo Ulug'bek loyihasi",t3d:"Mirzo Ulug'bek tumanida eski binolar qulandi, yangi tijorat majmuasi qurildi.",
  t4t:"Xalqaro sheriklar",t4d:"Janubiy Koreya va BAA investitsiya kompaniyalari bilan hamkorlik shartnomasi imzolandi.",
  t5t:"Uchtepa City boshlandi",t5d:"Eng yirik loyiha rasmiy e'lon qilindi. Yer uchastkasi hujjatlari rasmiylashtirilib, loyihalash ishlari boshlandi.",
  con_tag:"Kontaktlar",con_title:"Bog'lanish",
  con_lead:"Investitsiya bo'yicha barcha savollar, lot tanlash va muzokaralar uchun to'g'ridan-to'g'ri rahbariyat bilan bog'laning.",
  role_dir:"Direktor",role_dep:"Direktor o'rinbosari",ft_rights:"Barcha huquqlar himoyalangan."
},
ru:{
  nav_ind:"Показатели",nav_lots:"Лоты",nav_price:"Цены",nav_about:"О нас",nav_contacts:"Контакты",
    nav_faq:"Вопросы-Ответы",
  faq_tag:"Ответы на ключевые вопросы",faq_title:"О проекте",
  faq_lead:"Ответы, основанные на действующей нормативно-правовой базе Республики Узбекистан.",
  faq1_t:"Стоимость очистки территории и сроки",faq1_d:"Общая стоимость работ по очистке — <strong>$145.7 млн</strong>. Ориентировочные сроки — 9–12 месяцев.",faq1_l:"Правовое основание: ПКМ №414 — 10 июля 2024 г.",
  faq2_t:"Механизм возмещения затрат инвестора",faq2_d:"Порядок возмещения авансированных затрат урегулируется посредством отдельного договора займа на последующем этапе переговоров.",faq2_l:"Правовое основание: ПКМ №461 — 5 июня 2019 г. (п. 30)",
  faq3_t:"Прибрежный парк и границы проекта",faq3_d:"Территория прибрежной зоны полностью включена в границы проекта. Пешеходная аллея вдоль канала Бозсув.",faq3_l:"Правовое основание: ПКМ №414 — вдоль канала Бозсув и ул. Фозилтепа",
  faq4_t:"Коэффициент использования земли (FAR)",faq4_d:"<strong>FAR = 4</strong>, средняя этажность 33 этажа, общая площадь застройки <strong>1.1 млн м²</strong>.",faq4_l:"Правовое основание: ПКМ №83 — 28 февраля 2026 г.",
  faq5_t:"Состав территории проекта",faq5_note:"* Мастер-план разработан компанией ROX Group",
  ft1:"Общая площадь территории",ft2:"Площадь под строительство",ft3:"Компенсация и снос (за счёт инвестора)",ft4:"Стоянка для здравоохранения",ft5:"Зелёные зоны и дороги",ft5v:"Уточняется",ft6:"Общая сумма компенсации",
    nav_fut:"Будущее",
  fut_tag:"Uchtepa City — Будущее",fut_title:"Будущее проекта",fut_lead:"Представьте, как будет выглядеть Uchtepa City — через видео и визуализации.",
  t1t:"Основание компании",t1d:"В 2018 году начали деятельность с проекта Olmazor Business City.",
    nav_proj:"Проекты",
  proj_tag:"Реализованные проекты",proj_title:"Наш опыт",
  proj_lead:"До начала строительства Uchtepa City мы успешно реализовали крупнейшие проекты реконструкции Ташкента.",
  proj1_tag:"Завершён · 2022",proj1_desc:"На площади 23 га снесены ветхие строения. На их месте возведён современный бизнес-центр и жилой комплекс.",
  proj2_tag:"Завершён · 2023",proj2_desc:"44.5 га — один из крупнейших проектов реконструкции в Ташкенте. Старый квартал полностью обновлён.",
  lbl_before:"До",lbl_after:"После",
  hero_tag:"Инвестиционный проект • Ташкент, район Учтепа",
  hero_desc:"26 га — 31 жилой дом, 2 бизнес-центра, школа, детский сад и зелёная аллея вдоль канала Бозсув.",
  hero_btn:"Посмотреть показатели",
  kpi1:"Площадь застройки",kpi2:"Компенсация",kpi3:"Территория проекта",
  ind_tag:"Общие технико-экономические показатели",ind_title:"Показатели проекта",
  ind_lead:"Технико-экономические показатели на основе мастер-плана Uchtepa City.",
  i1:"Общая площадь территории лотов",i2:"Общая площадь застройки",i3:"Общая зелёная площадь",
  i4:"Количество бизнес-центров",i5:"Площадь бизнес-центров",i6:"Количество жилых домов",
  i7:"Этажность жилых домов",i8:"Общая площадь этажей жилых домов",i9:"Общее количество квартир",
  i10:"Численность населения",i11:"Площадь застройки школы",i12:"Этажность школы",
  i13:"Общая площадь этажей школы",i14:"Площадь застройки ДДУ",i15:"Этажность ДДУ",
  i16:"Общая площадь этажей ДДУ",i17:"Мест наземного паркинга",
  i18:"Общая площадь торговых этажей",i19:"Мест подземного паркинга",
  plan_cap:"Uchtepa City — Генеральный план",
  lots_tag:"Разделение территории на лоты",lots_title:"15 отдельных лотов",
  lots_lead:"Общая площадь 19.4 га. Каждый лот может быть оформлен как отдельная собственность.",
  th_n:"Лот",th_type:"Тип",th_area:"Площадь",
  b_res:"Жилой",b_biz:"Бизнес-центр",b_soc:"Школа",b_mtm:"Детский сад",b_park:"Паркинг",
  func_tag:"Функциональное распределение зданий",func_title:"Функциональные зоны",
  leg1_t:"Жилые дома",leg1_d:"31 здание, 18–22 этажа. Общая площадь этажей 819 809.6 м². 6 664 квартиры, 22 148 жителей.",
  leg2_t:"Бизнес-центры",leg2_d:"2 бизнес-центра. Общая площадь 246 328.8 м². Офисы, торговля и сфера услуг.",
  leg3_t:"Здание школы",leg3_d:"4-этажная школа. Площадь застройки 1 719.3 м², общая площадь этажей 6 877.2 м².",
  leg4_t:"ДДУ (Детский сад)",leg4_d:"2-этажное ДДУ. Площадь застройки 951.5 м², общая площадь этажей 1 903 м².",
  price_tag:"Цены",price_title:"Инвестиционная стоимость",
  price_lead:"Конкурентные цены и гибкие условия оплаты — наиболее выгодные условия для инвесторов.",
  p1_type:"Весь проект",p1_neg:"Договорная",p1_desc:"Полная стоимость участка 19.4 га со всеми 15 лотами и инфраструктурой.",
  p2_type:"Цена за 1 м² (средняя)",p2_neg:"Договорная",p2_desc:"Цена квадратного метра зависит от расположения и назначения лота.",
  p3_type:"Минимальный лот (№4)",p3_neg:"Договорная",p3_desc:"Наименьший лот — №4 (5 871.2 м², жилой). Удобная точка входа для малых инвесторов.",
  p_req:"Отправить запрос →",p_ask:"Узнать цену лота →",p_info:"Подробнее →",
  comp_title:"Средние цены соседних девелоперов (м² / $)",our_price:"Наша цена",our_val:"Договорная",
  about_tag:"О нас",about_title:"Наша история",
  ab1:"<strong>Uchtepa City</strong> — это не просто строительный проект. Это результат работы команды, годами менявшей облик городской среды Ташкента.",
  ab2:"Компания специализируется на сносе ветхого жилья и строительстве современных объектов, накопив значительный опыт в этой сфере.",
  ab3:"В каждом проекте мы уделяем особое внимание качеству строительства, экологическим нормам и интересам жителей. <strong>Uchtepa City</strong> — наш крупнейший и самый престижный проект.",
  t1t:"Основание компании",t1d:"Открыта специализированная фирма по строительству и реконструкции в Ташкенте.",
  t2t:"Первый крупный проект",t2d:"В Юнусабадском районе снесено ветхое жильё, построены современные многоэтажные здания.",
  t3t:"Проект Мирзо-Улугбека",t3d:"В районе Мирзо-Улугбека снесены строения, возведён новый торговый комплекс.",
  t4t:"Международные партнёры",t4d:"Подписаны договоры с инвестиционными компаниями из Южной Кореи и ОАЭ.",
  t5t:"Старт Uchtepa City",t5d:"Официально анонсирован крупнейший проект. Оформлены документы, начаты проектные работы.",
  con_tag:"Контакты",con_title:"Связаться",
  con_lead:"По всем вопросам инвестирования, выбора лота и переговорам — обращайтесь напрямую к руководству.",
  role_dir:"Директор",role_dep:"Заместитель директора",ft_rights:"Все права защищены."
},
en:{
  nav_ind:"Indicators",nav_lots:"Lots",nav_price:"Pricing",nav_about:"About",nav_contacts:"Contacts",
    nav_faq:"Q&A",
  faq_tag:"Answers to Key Questions",faq_title:"About the Project",
  faq_lead:"Answers based on the current regulatory framework of the Republic of Uzbekistan.",
  faq1_t:"Territory Clearance Cost & Timeline",faq1_d:"Total cost of clearance and site preparation — <strong>$145.7M</strong>. Estimated timeline — 9–12 months.",faq1_l:"Legal basis: CMR №414 — 10 July 2024",
  faq2_t:"Investor Cost Reimbursement Mechanism",faq2_d:"The reimbursement procedure for advanced costs will be regulated through a separate loan agreement at a subsequent negotiation stage.",faq2_l:"Legal basis: CMR №461 — 5 June 2019 (clause 30)",
  faq3_t:"Coastal Park & Project Boundaries",faq3_d:"The coastal zone is fully included in project boundaries. A green pedestrian promenade along the Bozsув canal.",faq3_l:"Legal basis: CMR №414 — along Bozsuv canal and Foziltepa street",
  faq4_t:"Floor Area Ratio (FAR)",faq4_d:"<strong>FAR = 4</strong>, average 33 floors, total construction area approx. <strong>1.1M m²</strong>.",faq4_l:"Legal basis: CMR №83 — 28 February 2026",
  faq5_t:"Project Territory Composition",faq5_note:"* Master plan developed by ROX Group",
  ft1:"Total territory area",ft2:"Construction area",ft3:"Compensation & demolition (by investor)",ft4:"Healthcare parking",ft5:"Green zones & roads",ft5v:"To be confirmed",ft6:"Total compensation amount",
    nav_fut:"Future",
  fut_tag:"Uchtepa City — Future",fut_title:"The Future of the Project",fut_lead:"Imagine what Uchtepa City will look like — through videos and visualisations.",
  t1t:"Company Founded",t1d:"In 2018 we began our activity with the Olmazor Business City project.",
    nav_proj:"Projects",
  proj_tag:"Completed Projects",proj_title:"Our Experience",
  proj_lead:"Before Uchtepa City, we successfully completed the largest urban reconstruction projects in Tashkent.",
  proj1_tag:"Completed · 2022",proj1_desc:"23 ha of deteriorated buildings demolished. A modern business centre and residential complex built in their place.",
  proj2_tag:"Completed · 2023",proj2_desc:"44.5 ha — one of the largest reconstruction projects in Tashkent. An entire old district completely renewed.",
  lbl_before:"Before",lbl_after:"After",
  hero_tag:"Investment Project • Tashkent, Uchtepa District",
  hero_desc:"26 ha — 31 residential buildings, 2 business centres, school, kindergarten and a green promenade along the Bozsuv canal.",
  hero_btn:"View Indicators",
  kpi1:"Construction Area",kpi2:"Compensation",kpi3:"Project Territory",
  ind_tag:"General Technical & Economic Indicators",ind_title:"Project Indicators",
  ind_lead:"Technical and economic indicators based on the Uchtepa City master plan.",
  i1:"Total lots territory area",i2:"Total construction area",i3:"Total green area",
  i4:"Number of business centres",i5:"Business centres area",i6:"Number of residential buildings",
  i7:"Residential building floors",i8:"Total residential floor area",i9:"Total number of apartments",
  i10:"Total population",i11:"School construction area",i12:"School floors",
  i13:"Total school floor area",i14:"Kindergarten construction area",i15:"Kindergarten floors",
  i16:"Total kindergarten floor area",i17:"Surface parking spaces",
  i18:"Total retail floor area",i19:"Underground parking spaces",
  plan_cap:"Uchtepa City — Master Plan",
  lots_tag:"Territory Lot Division",lots_title:"15 Individual Lots",
  lots_lead:"Total area 19.4 ha. Each lot can be registered as separate property.",
  th_n:"Lot",th_type:"Type",th_area:"Area",
  b_res:"Residential",b_biz:"Business Centre",b_soc:"School",b_mtm:"Kindergarten",b_park:"Parking",
  func_tag:"Functional Distribution of Buildings",func_title:"Functional Zones",
  leg1_t:"Residential Buildings",leg1_d:"31 buildings, 18–22 floors. Total floor area 819,809.6 m². 6,664 apartments, 22,148 residents.",
  leg2_t:"Business Centres",leg2_d:"2 business centres. Total area 246,328.8 m². Offices, retail and services.",
  leg3_t:"School Building",leg3_d:"4-storey school. Construction area 1,719.3 m², total floor area 6,877.2 m².",
  leg4_t:"Kindergarten (MTM)",leg4_d:"2-storey kindergarten. Construction area 951.5 m², total floor area 1,903 m².",
  price_tag:"Pricing",price_title:"Investment Value",
  price_lead:"Competitive pricing and flexible payment terms — the most favourable conditions for investors.",
  p1_type:"Entire Project",p1_neg:"Negotiable",p1_desc:"Full price of the 19.4 ha plot with all 15 lots and infrastructure.",
  p2_type:"Price per m² (average)",p2_neg:"Negotiable",p2_desc:"Price per square metre depends on lot location and purpose.",
  p3_type:"Minimum Lot (№4)",p3_neg:"Negotiable",p3_desc:"Smallest lot — №4 (5,871.2 m², residential). Convenient entry point for smaller investors.",
  p_req:"Send Inquiry →",p_ask:"Ask for Lot Price →",p_info:"More Details →",
  comp_title:"Neighbouring developers' average prices (m² / $)",our_price:"Our Price",our_val:"Negotiable",
  about_tag:"About",about_title:"Our Story",
  ab1:"<strong>Uchtepa City</strong> is more than a construction project. It is the result of a team that has spent years transforming Tashkent's urban environment.",
  ab2:"The company specialises in demolishing deteriorated housing and building modern facilities, with extensive experience in the field.",
  ab3:"In every project we focus on construction quality, environmental standards and community interests. <strong>Uchtepa City</strong> is our largest and most prestigious project.",
  t1t:"Company Founded",t1d:"A specialised construction and reconstruction firm opened in Tashkent.",
  t2t:"First Major Project",t2d:"Old housing demolished in Yunusabad district, replaced by modern multi-storey buildings.",
  t3t:"Mirzo-Ulugbek Project",t3d:"Buildings demolished in Mirzo-Ulugbek district; new commercial complex built.",
  t4t:"International Partners",t4d:"Partnership agreements signed with investment companies from South Korea and the UAE.",
  t5t:"Uchtepa City Launched",t5d:"Flagship project officially announced. Land documents formalised, design work started.",
  con_tag:"Contacts",con_title:"Get in Touch",
  con_lead:"For all investment questions, lot selection and negotiations — contact management directly.",
  role_dir:"Director",role_dep:"Deputy Director",ft_rights:"All rights reserved."
},
vi:{
  nav_ind:"Chỉ số",nav_lots:"Lô đất",nav_price:"Giá cả",nav_about:"Về chúng tôi",nav_contacts:"Liên hệ",
    nav_faq:"Hỏi-Đáp",
  faq_tag:"Trả lời các câu hỏi chính",faq_title:"Về dự án",
  faq_lead:"Các câu trả lời dựa trên khung pháp lý hiện hành của Cộng hòa Uzbekistan.",
  faq1_t:"Chi phí giải phóng mặt bằng và tiến độ",faq1_d:"Tổng chi phí giải phóng mặt bằng — <strong>$145.7M</strong>. Thời gian dự kiến — 9–12 tháng.",faq1_l:"Cơ sở pháp lý: NQ №414 — 10 tháng 7 năm 2024",
  faq2_t:"Cơ chế hoàn trả chi phí nhà đầu tư",faq2_d:"Thủ tục hoàn trả chi phí ứng trước sẽ được điều chỉnh thông qua hợp đồng vay riêng biệt.",faq2_l:"Cơ sở pháp lý: NQ №461 — 5 tháng 6 năm 2019 (điều 30)",
  faq3_t:"Công viên ven sông và ranh giới dự án",faq3_d:"Vùng ven sông được đưa vào ranh giới dự án. Đại lộ xanh dọc kênh Bozsuv.",faq3_l:"Cơ sở pháp lý: NQ №414 — dọc kênh Bozsuv và phố Foziltepa",
  faq4_t:"Hệ số sử dụng đất (FAR)",faq4_d:"<strong>FAR = 4</strong>, trung bình 33 tầng, tổng diện tích xây dựng khoảng <strong>1.1 triệu m²</strong>.",faq4_l:"Cơ sở pháp lý: NQ №83 — 28 tháng 2 năm 2026",
  faq5_t:"Thành phần lãnh thổ dự án",faq5_note:"* Quy hoạch tổng thể được phát triển bởi ROX Group",
  ft1:"Tổng diện tích",ft2:"Diện tích xây dựng",ft3:"Bồi thường và phá dỡ (do nhà đầu tư)",ft4:"Bãi đỗ xe y tế",ft5:"Khu xanh và đường",ft5v:"Đang xác nhận",ft6:"Tổng số tiền bồi thường",
    nav_fut:"Tương lai",
  fut_tag:"Uchtepa City — Tương lai",fut_title:"Tương lai của dự án",fut_lead:"Hãy hình dung Uchtepa City sẽ trông như thế nào — qua video và hình ảnh trực quan.",
  t1t:"Thành lập công ty",t1d:"Năm 2018 chúng tôi bắt đầu hoạt động với dự án Olmazor Business City.",
    nav_proj:"Dự án",
  proj_tag:"Dự án đã hoàn thành",proj_title:"Kinh nghiệm của chúng tôi",
  proj_lead:"Trước Uchtepa City, chúng tôi đã hoàn thành thành công các dự án tái thiết đô thị lớn nhất Tashkent.",
  proj1_tag:"Hoàn thành · 2022",proj1_desc:"23 ha công trình xuống cấp bị phá dỡ. Trung tâm kinh doanh và khu dân cư hiện đại được xây dựng thay thế.",
  proj2_tag:"Hoàn thành · 2023",proj2_desc:"44.5 ha — một trong những dự án tái thiết lớn nhất ở Tashkent. Toàn bộ khu phố cũ được làm mới hoàn toàn.",
  lbl_before:"Trước",lbl_after:"Sau",
  hero_tag:"Dự án đầu tư • Tashkent, quận Uchtepa",
  hero_desc:"26 ha — 31 tòa nhà dân cư, 2 trung tâm kinh doanh, trường học, nhà trẻ và đại lộ xanh ven kênh Bozsuv.",
  hero_btn:"Xem chỉ số",
  kpi1:"Diện tích xây dựng",kpi2:"Bồi thường",kpi3:"Lãnh thổ dự án",
  ind_tag:"Chỉ số kỹ thuật - kinh tế tổng hợp",ind_title:"Chỉ số dự án",
  ind_lead:"Các chỉ số kỹ thuật và kinh tế dựa trên quy hoạch tổng thể Uchtepa City.",
  i1:"Tổng diện tích vùng lô",i2:"Tổng diện tích xây dựng",i3:"Tổng diện tích xanh",
  i4:"Số trung tâm kinh doanh",i5:"Diện tích trung tâm kinh doanh",i6:"Số tòa nhà dân cư",
  i7:"Số tầng nhà dân cư",i8:"Tổng diện tích sàn dân cư",i9:"Tổng số căn hộ",
  i10:"Dân số",i11:"Diện tích xây dựng trường học",i12:"Số tầng trường học",
  i13:"Tổng diện tích sàn trường học",i14:"Diện tích xây dựng nhà trẻ",i15:"Số tầng nhà trẻ",
  i16:"Tổng diện tích sàn nhà trẻ",i17:"Chỗ đỗ xe mặt đất",
  i18:"Tổng diện tích sàn bán lẻ",i19:"Chỗ đỗ xe ngầm",
  plan_cap:"Uchtepa City — Quy hoạch tổng thể",
  lots_tag:"Phân chia vùng thành các lô",lots_title:"15 lô riêng lẻ",
  lots_lead:"Tổng diện tích 19.4 ha. Mỗi lô có thể được đăng ký như tài sản riêng biệt.",
  th_n:"Lô",th_type:"Loại",th_area:"Diện tích",
  b_res:"Dân cư",b_biz:"Trung tâm KD",b_soc:"Trường học",b_mtm:"Nhà trẻ",b_park:"Bãi đỗ xe",
  func_tag:"Phân bổ chức năng các tòa nhà",func_title:"Khu chức năng",
  leg1_t:"Nhà dân cư",leg1_d:"31 tòa, 18–22 tầng. Tổng diện tích sàn 819.809,6 m². 6.664 căn hộ, 22.148 cư dân.",
  leg2_t:"Trung tâm kinh doanh",leg2_d:"2 trung tâm. Tổng diện tích 246.328,8 m². Văn phòng, thương mại và dịch vụ.",
  leg3_t:"Tòa nhà trường học",leg3_d:"Trường 4 tầng. Diện tích xây dựng 1.719,3 m², tổng diện tích sàn 6.877,2 m².",
  leg4_t:"Nhà trẻ (MTM)",leg4_d:"Nhà trẻ 2 tầng. Diện tích xây dựng 951,5 m², tổng diện tích sàn 1.903 m².",
  price_tag:"Giá cả",price_title:"Giá trị đầu tư",
  price_lead:"Giá cạnh tranh và điều khoản thanh toán linh hoạt — điều kiện thuận lợi nhất cho nhà đầu tư.",
  p1_type:"Toàn bộ dự án",p1_neg:"Thương lượng",p1_desc:"Giá đầy đủ cho 19.4 ha với tất cả 15 lô và cơ sở hạ tầng.",
  p2_type:"Giá mỗi m² (TB)",p2_neg:"Thương lượng",p2_desc:"Giá mỗi mét vuông phụ thuộc vào vị trí và mục đích lô.",
  p3_type:"Lô tối thiểu (№4)",p3_neg:"Thương lượng",p3_desc:"Lô nhỏ nhất — №4 (5.871,2 m², dân cư). Điểm vào tiện lợi cho nhà đầu tư nhỏ.",
  p_req:"Gửi yêu cầu →",p_ask:"Hỏi giá lô →",p_info:"Chi tiết hơn →",
  comp_title:"Giá trung bình của các chủ đầu tư lân cận (m² / $)",our_price:"Giá của chúng tôi",our_val:"Thương lượng",
  about_tag:"Về chúng tôi",about_title:"Lịch sử của chúng tôi",
  ab1:"<strong>Uchtepa City</strong> không chỉ là dự án xây dựng. Đây là thành quả của đội ngũ nhiều năm cải tạo không gian đô thị Tashkent.",
  ab2:"Công ty chuyên về phá dỡ nhà cũ và xây dựng công trình hiện đại, với kinh nghiệm phong phú trong lĩnh vực này.",
  ab3:"Trong mọi dự án, chúng tôi chú trọng chất lượng xây dựng, tiêu chuẩn môi trường và lợi ích cộng đồng. <strong>Uchtepa City</strong> là dự án lớn nhất và uy tín nhất của chúng tôi.",
  t1t:"Thành lập công ty",t1d:"Mở công ty xây dựng và cải tạo tại Tashkent.",
  t2t:"Dự án lớn đầu tiên",t2d:"Phá dỡ nhà cũ ở quận Yunusabad, xây các tòa nhà cao tầng hiện đại.",
  t3t:"Dự án Mirzo-Ulugbek",t3d:"Phá dỡ công trình ở quận Mirzo-Ulugbek, xây khu thương mại mới.",
  t4t:"Đối tác quốc tế",t4d:"Ký kết hợp tác với các công ty đầu tư Hàn Quốc và UAE.",
  t5t:"Khởi động Uchtepa City",t5d:"Dự án chính thức được công bố. Hoàn thiện hồ sơ đất, bắt đầu thiết kế.",
  con_tag:"Liên hệ",con_title:"Liên hệ với chúng tôi",
  con_lead:"Mọi câu hỏi về đầu tư, chọn lô và đàm phán — hãy liên hệ trực tiếp với ban lãnh đạo.",
  role_dir:"Giám đốc",role_dep:"Phó giám đốc",ft_rights:"Bảo lưu mọi quyền."
}
};

let currentLang='uz';
function setLang(lang){
  currentLang=lang;
  document.querySelectorAll('.lb').forEach(b=>b.classList.toggle('active',b.textContent.toLowerCase()===lang));
  const t=T[lang];
  document.querySelectorAll('[data-i]').forEach(el=>{
    const k=el.getAttribute('data-i');
    if(t[k]!==undefined) el.innerHTML=t[k];
  });
}
