const T = {
uz:{
  nav_ind:"Ko'rsatkichlar",nav_lots:"Lotlar",nav_price:"Narxlar",nav_about:"Biz haqimizda",nav_contacts:"Kontaktlar",
    proj3_tag:"Faoliyatda · 2021",proj3_desc:"Prezident qarori asosida tashkil etilgan zamonaviy sanoat zonasi. O'zbekiston Respublikasi Bosh vaziri va Toshkent shahar hokimining ishonchi bilan bu loyiha bizning jamoamizga topshirildi.",
    t_yht:"Yangihayot Industrial Texnopark",t_yhd:"Prezident qarori asosida zamonaviy sanoat zonasi tashkil etildi. O'zbekiston Respublikasi Bosh vaziri va Toshkent shahar hokimining ishonchi bilan bu loyiha ham bizning jamoamizga topshirildi.",
    nav_adv:"Afzalliklar",
  adv_tag:"Nega Uchtepa City?",adv_title:"Investitsiya afzalliklari",
  adv_lead:"Uchtepa City — investorlar uchun bir qator noyob strategik va huquqiy afzalliklarga ega loyiha.",
  adv1_t:"Kommunikatsiyalar investor qizil chizig'igacha",adv1_d:"Barcha kommunikatsiyalar (suv, gaz, elektr, kanalizatsiya) investor tomonini qizil chizig'igacha bepul yetkaziladi.",
  adv2_t:"Davlat tomonidan to'liq qo'llab-quvvatlash",adv2_d:"Loyiha O'zbekiston Respublikasi VMQ qarorlari bilan mustahkamlangan. To'liq huquqiy himoya va davlat kafolati.",
  adv3_t:"30+ qavatli binolar qurish huquqi",adv3_d:"Uchtepa City — Toshkentda 30 qavatdan baland binolar qurish mumkin bo'lgan kam sonli loyihalardan biri. FAR = 4.",
  adv4_t:"Snos direksiya tomonidan amalga oshiriladi",adv4_d:"Turar-joy va noturar binolarni qulash ishlarini direksiya amalga oshiradi. Investor bu yukni o'z zimmasiga olmaydi.",
  adv5_t:"3 gektar erkin yer — darhol qurilish mumkin",adv5_d:"Hozirda 3 gektar bo'sh yer mavjud — snos va ko'chirishni kutmasdan darhol qurilishni boshlash mumkin.",
  adv6_t:"Qo'shni yerlar $1 100/m² — bizda $600/m²",adv6_d:"Loyihadan 1.4 km uzoqlikdagi tayyor hujjatli yerlarda narx $1 100/m². Bizning loyihada o'rtacha narx — <strong>$600/m²</strong>.",
  adv7_t:"1.81 km qirg'oq liniyasi — Bozsuv kanali",adv7_d:"Loyiha 1.81 km uzunlikdagi Bozsuv kanali qirg'og'i bo'ylab joylashgan. Issiq iqlimda suv yaqinidagi loyihalar ayniqsa istiqbolli.",
  adv8_t:"Toshkentning eng yashil tumanlaridan biri",adv8_d:"Uchtepa tumani — ko'p yashilliklar, parklar va bog'lar bilan Toshkentdagi eng ekologik tumanlardan biri.",
  adv9_t:"Strategik joylashuv",
  loc1:"Kichik halqa yo'li",loc1d:"Yaqinida",loc2:"Tashkent City",loc3:"Xalqaro aeroport",loc4:"Markaziy vokzal",loc5:"Metro",loc6:"Qo'shni yer (hujjatli)",
    nav_faq:"Savol-Javob",
  faq_tag:"Asosiy savollarga javoblar",faq_title:"Loyiha haqida",
  faq_lead:"O'zbekiston Respublikasi Vazirlar Mahkamasi qarorlari asosida tayyorlangan javoblar.",
  faq1_t:"Hududni tozalash qiymati va muddati",faq1_d:"Hududni tozalash va tayyorlash bo'yicha umumiy xarajatlar <strong>$145.7 mln</strong>. Muddati — 9–12 oy.",faq1_l:"Huquqiy asos: VMQ №414 — 10 iyul 2024 yil",
  faq2_t:"Investor xarajatlarini qoplash",faq2_d:"Avanslanган xarajatlarni qoplash keyingi muzokaralar bosqichida alohida qarz shartnomasi orqali tartibga solinadi.",faq2_l:"Huquqiy asos: VMQ №461 — 5 iyun 2019 yil (30-band)",
  faq3_t:"Qirg'oq parki va loyiha chegaralari",faq3_d:"Qirg'oq zonasi to'liq loyiha chegaralariga kiritilgan. Bozsuv kanali bo'ylab yashil alleya.",faq3_l:"Huquqiy asos: VMQ №414 — Bozsuv kanali va Foziltepa ko'chasi",
  faq4_t:"Yer foydalanish koeffitsienti (FAR)",faq4_d:"<strong>FAR = 4</strong>, o'rtacha 33 qavat, umumiy qurilish maydoni <strong>1.1 mln m²</strong>.",faq4_l:"Huquqiy asos: VMQ №83 — 28 fevral 2026 yil",
  faq5_t:"Loyiha hududining tarkibi",faq5_note:"* Master-plan ROX Group kompaniyasi tomonidan ishlab chiqilgan",
  ft1:"Umumiy maydon",ft2:"Qurilish maydoni",ft3:"Kompensatsiya va qulash",ft4:"Sog'liqni saqlash uchun avtoturargoh",ft5:"Yashil zonalar va yo'llar",ft5v:"Aniqlanmoqda",ft6:"Umumiy kompensatsiya summasi",
    nav_fut:"Kelajak",
  fut_tag:"Uchtepa City — Kelajak",fut_title:"Loyihaning kelajagi",fut_lead:"Uchtepa City qanday ko'rinishda bo'lishini tasavvur qiling — video va vizualizatsiyalar orqali.",
  t1t:"Kompaniya tashkil etildi",t1d:"2018 yilda Olmazor Business City loyihasi bilan faoliyatimiz boshlandi.",
    nav_proj:"Loyihalar",
  proj_tag:"Amalga oshirilgan loyihalar",proj_title:"Bizning tajribamiz",
  proj1_tag:"Tugallangan · 2022",proj1_desc:"23 gektar maydonida eski va buzilgan binolar qulandi. O'rniga zamonaviy biznes markazi va turar-joy majmuasi qurildi.",
  proj2_tag:"Tugallangan · 2023",proj2_desc:"44.5 gektar — Toshkentdagi eng yirik rekonstruksiya loyihalaridan biri. Eski mahalla to'liq yangilandi.",
  lbl_before:"Oldin",lbl_after:"Keyin",
  hero_tag:"Investitsiya loyihasi • Toshkent, Uchtepa tumani",
  hero_desc:"26 gektar maydonida zamonaviy shahar — 31 ta turar-joy binosi, 2 ta biznes markaz, maktab, MTM va Bozsuv kanali bo'ylab yashil alleya.",
  hero_btn:"Ko'rsatkichlarni ko'rish",
  kpi1:"Qurilish maydoni",kpi2:"Kompensatsiya",kpi3:"Loyiha hududi",
  ind_tag:"Umumiy texnik-iqtisodiy ko'rsatkichlar",ind_title:"Loyiha ko'rsatkichlari",
  ind_lead:"Uchtepa City master-plani asosida hisoblangan texnik-iqtisodiy ko'rsatkichlar.",
  i1:"Lotlar hududi umumiy maydoni",i2:"Umumiy qurilish maydoni",i3:"Umumiy yashil maydon",
  i4:"Biznes markazlari soni",i5:"Biznes markazlari maydoni",i6:"Turar-joy binolari soni",
  i7:"Turar-joy qavatlar soni",i8:"Turar-joy umumiy qavatlar maydoni",i9:"Umumiy xonadonlar soni",
  i10:"Aholi soni",i11:"Maktab qurilish maydoni",i12:"Maktab qavatlar soni",
  i13:"Maktab qavatlar umumiy maydoni",i14:"MTM qurilish maydoni",i15:"MTM qavatlar soni",
  i16:"MTM qavatlar maydoni",i17:"Yer usti avtoturargoh o'rinlari",
  i18:"Savdo sotiq qavatlar umumiy maydoni",i19:"Yer osti avtoturargoh o'rinlari",
  plan_cap:"Uchtepa City — Umumiy bosh reja",
  lots_tag:"Hududning lotlarga bo'linishi",lots_title:"15 ta alohida lot",
  lots_lead:"Umumiy maydon 19.4 Ga. Har bir lot alohida mulk sifatida ro'yxatdan o'tkazilishi mumkin.",
  th_n:"Lot",th_type:"Tur",th_area:"Maydon",
  b_res:"Turar-joy",b_biz:"Biznes markaz",b_soc:"Maktab",b_mtm:"Bog'cha (MTM)",b_park:"Avtoturargoh",
  func_tag:"Binolarning funksional taqsimlashi",func_title:"Funksional zonalar",
  leg1_t:"Turar-joy binolari",leg1_d:"31 ta bino, 18–22 qavat. Umumiy qavatlar maydoni 819 809.6 m². 6 664 ta xonadon, 22 148 ta aholi.",
  leg2_t:"Biznes markazlari",leg2_d:"2 ta biznes markaz. Umumiy maydoni 246 328.8 m². Ofis, savdo va xizmat ko'rsatish zonalari.",
  leg3_t:"Maktab binosi",leg3_d:"4 qavatli maktab. Qurilish maydoni 1 719.3 m², umumiy qavatlar maydoni 6 877.2 m².",
  leg4_t:"MTM binosi (Bog'cha)",leg4_d:"2 qavatli MTM. Qurilish maydoni 951.5 m², umumiy qavatlar maydoni 1 903 m².",
  price_tag:"Narxlar",price_title:"Investitsiya qiymati",
  price_lead:"Raqobatbardosh narxlar va moslashuvchan to'lov shartlari bilan investorlar uchun eng qulay sharoitlar.",
  p1_type:"Butun loyiha",p1_desc:"Barcha lotlar va infratuzilma bilan birga 26 ga yer uchastkasining to'liq narxi. Kompensatsiya va qulash xarajatlari bilan.",
  p2_type:"1 m² narxi (o'rtacha)",p2_desc:"Lotning joylashuvi va maqsadiga qarab o'rtacha kvadrat metr narxi.",
  p3_type:"Minimal lot (№4)",p3_neg:"Kelishiladi",p3_desc:"Eng kichik lot — №4 (5 871.2 m², Turar-joy binosi). Kichik va o'rta investorlar uchun qulay kirish nuqtasi.",
  p_req:"So'rov yuborish →",p_ask:"Lot narxini so'rash →",p_info:"Batafsil ma'lumot →",
  comp_title:"Qo'shni developerlarning o'rtacha narxi (m² / $)",our_price:"Bizning narx",our_val:"$600 /m²",
  about_tag:"Biz haqimizda",about_title:"Direksiya <em>tajribasi</em>",
  ab1:"<strong>Direksiya</strong> 2018 yildan buyon yirik shaharsozlik loyihalarida investorlarni jalb qilish, hududlarni bo'shatish, kommunikatsiya va lotlarni tayyorlash jarayonlarida amaliy tajriba to'plagan.",
  ab2:"Olmazor Business City va Yunusobod Business City loyihalaridagi tajriba bugun <strong>Uchtepa City</strong> loyihasini investorlar uchun tayyorlashda qo'llanilmoqda.",
  ab3:"Uchtepa City joylashuvini xaritalarda ko'rishingiz mumkin:",
  t1t:"Direksiya tashkil etildi",t1d:"Olmazor Business City loyihasi ustida ish boshlandi: investor topildi, hudud bo'shatildi va yer maydoni investorga ajratib berildi. COVID-19 va karantin sababli to'liq bo'shatish 2021 yilgacha cho'zildi; qurilish ishlari 2023 yilda yakunlandi.",
  t2t:"Yunusobod Business City",t2d:"Yangi direksiya tashkil etildi, ammo asosiy jamoa saqlanib qoldi. Investorlar jalb qilindi; investor uchun ajratilgan yer maydoni 2022 yilgacha bo'shatib berildi, 2023 yilga kelib hududning 70-75% qismi tayyorlandi va keyingi bosqich boshqa jamoaga topshirildi.",
  t3t:"Uchtepa City biriktirildi",t3d:"Vazirlar Mahkamasi qarori asosida Uchtepa City loyihasi Olmazor Business City direksiyasiga biriktirib berildi.",
  t4t:"",t4d:"",
  map_google:"Google Maps",map_yandex:"Yandex Navigator",
  t5t:"Uchtepa City boshlandi",t5d:"Eng yirik loyiha rasmiy e'lon qilindi. Yer uchastkasi hujjatlari rasmiylashtirilib, loyihalash ishlari boshlandi.",
  con_tag:"Kontaktlar",con_title:"Bog'lanish",
  con_lead:"Investitsiya bo'yicha barcha savollar, lot tanlash va muzokaralar uchun to'g'ridan-to'g'ri rahbariyat bilan bog'laning.",
  role_dir:"Direktor",role_dep:"Direktor o'rinbosari",ft_rights:"Barcha huquqlar himoyalangan."
},
ru:{
  nav_ind:"Показатели",nav_lots:"Лоты",nav_price:"Цены",nav_about:"О нас",nav_contacts:"Контакты",
    proj3_tag:"В работе · 2021",proj3_desc:"Современная промышленная зона, основанная по постановлению Президента. По доверию Премьер-министра РУз и хакима города Ташкента этот проект был поручен нашей команде.",
    t_yht:"Yangihayot Industrial Texnopark",t_yhd:"По постановлению Президента основан Технопарк — современная промышленная зона. По доверию Премьер-министра РУз и хакима города Ташкента этот проект также был поручен нашей команде.",
    nav_adv:"Преимущества",
  adv_tag:"Почему Uchtepa City?",adv_title:"Инвестиционные преимущества",
  adv_lead:"Uchtepa City — проект с уникальными стратегическими и правовыми преимуществами для инвесторов.",
  adv1_t:"Коммуникации до красной линии инвестора",adv1_d:"Все коммуникации (вода, газ, электричество, канализация) подводятся до красной линии инвестора без дополнительных затрат.",
  adv2_t:"Полная государственная поддержка",adv2_d:"Проект закреплён постановлениями Кабинета Министров РУз. Полная правовая защита и государственная гарантия.",
  adv3_t:"Право строить выше 30 этажей",adv3_d:"Uchtepa City — один из немногих проектов в Ташкенте, где разрешено строительство зданий выше 30 этажей. FAR = 4.",
  adv4_t:"Снос осуществляет дирекция",adv4_d:"Снос жилых и нежилых строений выполняет дирекция. Инвестор не несёт этой нагрузки.",
  adv5_t:"3 га свободной земли — стройка сразу",adv5_d:"Уже сейчас доступно 3 га свободной земли — можно начать строительство, не дожидаясь сноса и переселения.",
  adv6_t:"Соседние участки $1 100/м² — у нас $600/м²",adv6_d:"Соседние участки с готовыми документами в 1.4 км стоят $1 100/м². Наша средняя цена — <strong>$600/м²</strong>.",
  adv7_t:"1.81 км береговой линии — канал Бозсув",adv7_d:"Проект расположен вдоль 1.81 км берега канала Бозсув. В условиях аномальной жары проекты у воды особенно перспективны.",
  adv8_t:"Один из самых зелёных районов Ташкента",adv8_d:"Район Учтепа — один из наиболее экологичных районов Ташкента с большим количеством зелени, парков и садов.",
  adv9_t:"Стратегическое расположение",
  loc1:"Малая кольцевая дорога",loc1d:"Рядом",loc2:"Tashkent City",loc3:"Международный аэропорт",loc4:"Центральный вокзал",loc5:"Метро",loc6:"Соседний участок (с документами)",
    nav_faq:"Вопросы-Ответы",
  faq_tag:"Ответы на ключевые вопросы",faq_title:"О проекте",
  faq_lead:"Ответы, основанные на действующей нормативно-правовой базе Республики Узбекистан.",
  faq1_t:"Стоимость очистки территории и сроки",faq1_d:"Общая стоимость работ по очистке — <strong>$145.7 млн</strong>. Ориентировочные сроки — 9–12 месяцев.",faq1_l:"Правовое основание: ПКМ №414 — 10 июля 2024 г.",
  faq2_t:"Механизм возмещения затрат инвестора",faq2_d:"Порядок возмещения авансированных затрат урегулируется посредством отдельного договора займа на последующем этапе переговоров.",faq2_l:"Правовое основание: ПКМ №461 — 5 июня 2019 г. (п. 30)",
  faq3_t:"Прибрежный парк и границы проекта",faq3_d:"Территория прибрежной зоны полностью включена в границы проекта. Пешеходная аллея вдоль канала Бозсув.",faq3_l:"Правовое основание: ПКМ №414 — вдоль канала Бозсув и ул. Фозилтепа",
  faq4_t:"Коэффициент использования земли (FAR)",faq4_d:"<strong>FAR = 4</strong>, средняя этажность 33 этажа, общая площадь застройки <strong>1.1 млн м²</strong>.",faq4_l:"Правовое основание: ПКМ №83 — 28 февраля 2026 г.",
  faq5_t:"Состав территории проекта",faq5_note:"* Мастер-план разработан компанией ROX Group",
  ft1:"Общая площадь территории",ft2:"Площадь под строительство",ft3:"Компенсация и снос (за счёт инвестора)",ft4:"Стоянка для здравоохранения",ft5:"Зелёные зоны и дороги",ft5v:"Уточняется",ft6:"Общая сумма компенсации",
    nav_fut:"Будущее",
  fut_tag:"Uchtepa City — Будущее",fut_title:"Будущее проекта",fut_lead:"Представьте, как будет выглядеть Uchtepa City — через видео и визуализации.",
  t1t:"Основание компании",t1d:"В 2018 году начали деятельность с проекта Olmazor Business City.",
    nav_proj:"Проекты",
  proj_tag:"Реализованные проекты",proj_title:"Наш опыт",
  proj1_tag:"Завершён · 2022",proj1_desc:"На площади 23 га снесены ветхие строения. На их месте возведён современный бизнес-центр и жилой комплекс.",
  proj2_tag:"Завершён · 2023",proj2_desc:"44.5 га — один из крупнейших проектов реконструкции в Ташкенте. Старый квартал полностью обновлён.",
  lbl_before:"До",lbl_after:"После",
  hero_tag:"Инвестиционный проект • Ташкент, район Учтепа",
  hero_desc:"26 га — 31 жилой дом, 2 бизнес-центра, школа, детский сад и зелёная аллея вдоль канала Бозсув.",
  hero_btn:"Посмотреть показатели",
  kpi1:"Площадь застройки",kpi2:"Компенсация",kpi3:"Территория проекта",
  ind_tag:"Общие технико-экономические показатели",ind_title:"Показатели проекта",
  ind_lead:"Технико-экономические показатели на основе мастер-плана Uchtepa City.",
  i1:"Общая площадь территории лотов",i2:"Общая площадь застройки",i3:"Общая зелёная площадь",
  i4:"Количество бизнес-центров",i5:"Площадь бизнес-центров",i6:"Количество жилых домов",
  i7:"Этажность жилых домов",i8:"Общая площадь этажей жилых домов",i9:"Общее количество квартир",
  i10:"Численность населения",i11:"Площадь застройки школы",i12:"Этажность школы",
  i13:"Общая площадь этажей школы",i14:"Площадь застройки ДДУ",i15:"Этажность ДДУ",
  i16:"Общая площадь этажей ДДУ",i17:"Мест наземного паркинга",
  i18:"Общая площадь торговых этажей",i19:"Мест подземного паркинга",
  plan_cap:"Uchtepa City — Генеральный план",
  lots_tag:"Разделение территории на лоты",lots_title:"15 отдельных лотов",
  lots_lead:"Общая площадь 19.4 га. Каждый лот может быть оформлен как отдельная собственность.",
  th_n:"Лот",th_type:"Тип",th_area:"Площадь",
  b_res:"Жилой",b_biz:"Бизнес-центр",b_soc:"Школа",b_mtm:"Детский сад",b_park:"Паркинг",
  func_tag:"Функциональное распределение зданий",func_title:"Функциональные зоны",
  leg1_t:"Жилые дома",leg1_d:"31 здание, 18–22 этажа. Общая площадь этажей 819 809.6 м². 6 664 квартиры, 22 148 жителей.",
  leg2_t:"Бизнес-центры",leg2_d:"2 бизнес-центра. Общая площадь 246 328.8 м². Офисы, торговля и сфера услуг.",
  leg3_t:"Здание школы",leg3_d:"4-этажная школа. Площадь застройки 1 719.3 м², общая площадь этажей 6 877.2 м².",
  leg4_t:"ДДУ (Детский сад)",leg4_d:"2-этажное ДДУ. Площадь застройки 951.5 м², общая площадь этажей 1 903 м².",
  price_tag:"Цены",price_title:"Инвестиционная стоимость",
  price_lead:"Конкурентные цены и гибкие условия оплаты — наиболее выгодные условия для инвесторов.",
  p1_type:"Весь проект",p1_desc:"Полная стоимость 26 га со всеми лотами и инфраструктурой. Включает компенсацию и снос.",
  p2_type:"Цена за 1 м² (средняя)",p2_desc:"Средняя цена квадратного метра в зависимости от расположения и назначения лота.",
  p3_type:"Минимальный лот №4 (E-auksion)",p3_desc:"Цена за м² при покупке лота №4 через E-auksion. Площадь лота 5 871.2 м².",
  p_req:"Отправить запрос →",p_ask:"Узнать цену лота →",p_info:"Подробнее →",
  comp_title:"Средние цены соседних девелоперов (м² / $)",our_price:"Наша цена",our_val:"$600 /m²",
  about_tag:"О нас",about_title:"Опыт <em>дирекции</em>",
  ab1:"<strong>Дирекция</strong> с 2018 года накопила практический опыт в привлечении инвесторов, освобождении территорий, подготовке коммуникаций и лотов для крупных градостроительных проектов.",
  ab2:"Опыт Olmazor Business City и Yunusobod Business City сегодня применяется при подготовке <strong>Uchtepa City</strong> для инвесторов.",
  ab3:"Расположение Uchtepa City можно посмотреть на картах:",
  t1t:"Создана дирекция",t1d:"Началась работа над Olmazor Business City: был найден инвестор, территория освобождалась и земельный участок передавался инвестору. Из-за COVID-19 и карантина полное освобождение территории продлилось до 2021 года; строительные работы завершились в 2023 году.",
  t2t:"Yunusobod Business City",t2d:"Была создана новая дирекция, при этом основная команда сохранилась. Были привлечены инвесторы; выделенная инвестору территория освобождалась до 2022 года, к 2023 году было подготовлено 70-75% участка, после чего следующий этап был передан другой команде.",
  t3t:"Передан проект Uchtepa City",t3d:"На основании постановления Кабинета Министров проект Uchtepa City был закреплён за дирекцией Olmazor Business City.",
  t4t:"",t4d:"",
  map_google:"Google Maps",map_yandex:"Яндекс Навигатор",
  t5t:"Старт Uchtepa City",t5d:"Официально анонсирован крупнейший проект. Оформлены документы, начаты проектные работы.",
  con_tag:"Контакты",con_title:"Связаться",
  con_lead:"По всем вопросам инвестирования, выбора лота и переговорам — обращайтесь напрямую к руководству.",
  role_dir:"Директор",role_dep:"Заместитель директора",ft_rights:"Все права защищены."
},
en:{
  nav_ind:"Indicators",nav_lots:"Lots",nav_price:"Pricing",nav_about:"About",nav_contacts:"Contacts",
    proj3_tag:"Active · 2021",proj3_desc:"A modern industrial zone established by Presidential decree. Entrusted by the Prime Minister of Uzbekistan and the Mayor of Tashkent, this project was assigned to our team.",
    t_yht:"Yangihayot Industrial Texnopark",t_yhd:"By Presidential decree, the Yangihayot Industrial Technopark — a modern industrial zone — was established. Entrusted by the Prime Minister of Uzbekistan and the Mayor of Tashkent, this project was also assigned to our team.",
    nav_adv:"Advantages",
  adv_tag:"Why Uchtepa City?",adv_title:"Investment Advantages",
  adv_lead:"Uchtepa City offers investors a unique set of strategic and legal advantages.",
  adv1_t:"All utilities to investor's red line",adv1_d:"All utilities (water, gas, electricity, sewage) are delivered to the investor's red line at no additional cost.",
  adv2_t:"Full government support",adv2_d:"The project is backed by decrees of the Cabinet of Ministers of Uzbekistan. Full legal protection and state guarantee.",
  adv3_t:"Right to build 30+ storey buildings",adv3_d:"Uchtepa City is one of the few projects in Tashkent where buildings over 30 storeys are permitted. FAR = 4.",
  adv4_t:"Demolition carried out by the Directorate",adv4_d:"Demolition of residential and non-residential buildings is carried out by the Directorate. The investor does not bear this burden.",
  adv5_t:"3 ha of free land — construction can start now",adv5_d:"3 ha of vacant land is already available — construction can begin immediately without waiting for demolition.",
  adv6_t:"Neighbouring land $1,100/m² — ours $600/m²",adv6_d:"Neighbouring plots with ready documents 1.4 km away cost $1,100/m². Our average price is <strong>$600/m²</strong>.",
  adv7_t:"1.81 km shoreline — Bozsuv canal",adv7_d:"The project runs along 1.81 km of the Bozsuv canal. In conditions of extreme heat, waterfront projects are especially promising.",
  adv8_t:"One of Tashkent's greenest districts",adv8_d:"Uchtepa district is one of Tashkent's most ecological areas, with abundant greenery, parks and gardens.",
  adv9_t:"Strategic location",
  loc1:"Small ring road",loc1d:"Adjacent",loc2:"Tashkent City",loc3:"International Airport",loc4:"Central Railway Station",loc5:"Metro",loc6:"Neighbouring plot (with documents)",
    nav_faq:"Q&A",
  faq_tag:"Answers to Key Questions",faq_title:"About the Project",
  faq_lead:"Answers based on the current regulatory framework of the Republic of Uzbekistan.",
  faq1_t:"Territory Clearance Cost & Timeline",faq1_d:"Total cost of clearance and site preparation — <strong>$145.7M</strong>. Estimated timeline — 9–12 months.",faq1_l:"Legal basis: CMR №414 — 10 July 2024",
  faq2_t:"Investor Cost Reimbursement Mechanism",faq2_d:"The reimbursement procedure for advanced costs will be regulated through a separate loan agreement at a subsequent negotiation stage.",faq2_l:"Legal basis: CMR №461 — 5 June 2019 (clause 30)",
  faq3_t:"Coastal Park & Project Boundaries",faq3_d:"The coastal zone is fully included in project boundaries. A green pedestrian promenade along the Bozsув canal.",faq3_l:"Legal basis: CMR №414 — along Bozsuv canal and Foziltepa street",
  faq4_t:"Floor Area Ratio (FAR)",faq4_d:"<strong>FAR = 4</strong>, average 33 floors, total construction area approx. <strong>1.1M m²</strong>.",faq4_l:"Legal basis: CMR №83 — 28 February 2026",
  faq5_t:"Project Territory Composition",faq5_note:"* Master plan developed by ROX Group",
  ft1:"Total territory area",ft2:"Construction area",ft3:"Compensation & demolition (by investor)",ft4:"Healthcare parking",ft5:"Green zones & roads",ft5v:"To be confirmed",ft6:"Total compensation amount",
    nav_fut:"Future",
  fut_tag:"Uchtepa City — Future",fut_title:"The Future of the Project",fut_lead:"Imagine what Uchtepa City will look like — through videos and visualisations.",
  t1t:"Company Founded",t1d:"In 2018 we began our activity with the Olmazor Business City project.",
    nav_proj:"Projects",
  proj_tag:"Completed Projects",proj_title:"Our Experience",
  proj1_tag:"Completed · 2022",proj1_desc:"23 ha of deteriorated buildings demolished. A modern business centre and residential complex built in their place.",
  proj2_tag:"Completed · 2023",proj2_desc:"44.5 ha — one of the largest reconstruction projects in Tashkent. An entire old district completely renewed.",
  lbl_before:"Before",lbl_after:"After",
  hero_tag:"Investment Project • Tashkent, Uchtepa District",
  hero_desc:"26 ha — 31 residential buildings, 2 business centres, school, kindergarten and a green promenade along the Bozsuv canal.",
  hero_btn:"View Indicators",
  kpi1:"Construction Area",kpi2:"Compensation",kpi3:"Project Territory",
  ind_tag:"General Technical & Economic Indicators",ind_title:"Project Indicators",
  ind_lead:"Technical and economic indicators based on the Uchtepa City master plan.",
  i1:"Total lots territory area",i2:"Total construction area",i3:"Total green area",
  i4:"Number of business centres",i5:"Business centres area",i6:"Number of residential buildings",
  i7:"Residential building floors",i8:"Total residential floor area",i9:"Total number of apartments",
  i10:"Total population",i11:"School construction area",i12:"School floors",
  i13:"Total school floor area",i14:"Kindergarten construction area",i15:"Kindergarten floors",
  i16:"Total kindergarten floor area",i17:"Surface parking spaces",
  i18:"Total retail floor area",i19:"Underground parking spaces",
  plan_cap:"Uchtepa City — Master Plan",
  lots_tag:"Territory Lot Division",lots_title:"15 Individual Lots",
  lots_lead:"Total area 19.4 ha. Each lot can be registered as separate property.",
  th_n:"Lot",th_type:"Type",th_area:"Area",
  b_res:"Residential",b_biz:"Business Centre",b_soc:"School",b_mtm:"Kindergarten",b_park:"Parking",
  func_tag:"Functional Distribution of Buildings",func_title:"Functional Zones",
  leg1_t:"Residential Buildings",leg1_d:"31 buildings, 18–22 floors. Total floor area 819,809.6 m². 6,664 apartments, 22,148 residents.",
  leg2_t:"Business Centres",leg2_d:"2 business centres. Total area 246,328.8 m². Offices, retail and services.",
  leg3_t:"School Building",leg3_d:"4-storey school. Construction area 1,719.3 m², total floor area 6,877.2 m².",
  leg4_t:"Kindergarten (MTM)",leg4_d:"2-storey kindergarten. Construction area 951.5 m², total floor area 1,903 m².",
  price_tag:"Pricing",price_title:"Investment Value",
  price_lead:"Competitive pricing and flexible payment terms — the most favourable conditions for investors.",
  p1_type:"Entire Project",p1_desc:"Full price of the 26 ha plot with all lots and infrastructure. Includes compensation and demolition.",
  p2_type:"Price per m² (average)",p2_desc:"Average price per square metre depending on lot location and purpose.",
  p3_type:"Minimum Lot №4 (E-auksion)",p3_desc:"Price per m² when purchasing lot №4 via E-auksion. Lot area 5,871.2 m².",
  p_req:"Send Inquiry →",p_ask:"Ask for Lot Price →",p_info:"More Details →",
  comp_title:"Neighbouring developers' average prices (m² / $)",our_price:"Our Price",our_val:"$600 /m²",
  about_tag:"About",about_title:"Directorate <em>Experience</em>",
  ab1:"Since 2018, the <strong>Directorate</strong> has built practical experience in attracting investors, clearing territories, preparing utilities and readying lots for major urban development projects.",
  ab2:"The experience gained through Olmazor Business City and Yunusobod Business City is now applied to preparing <strong>Uchtepa City</strong> for investors.",
  ab3:"You can view the Uchtepa City location on maps:",
  t1t:"Directorate established",t1d:"Work began on Olmazor Business City: an investor was found, the territory was cleared and the land plot was allocated to the investor. Due to COVID-19 and quarantine, full clearance extended until 2021; construction was completed in 2023.",
  t2t:"Yunusobod Business City",t2d:"A new directorate was formed while the core team remained. Investors were attracted; the land allocated to the investor was cleared by 2022, 70-75% of the territory was prepared by 2023, and the next stage was transferred to another team.",
  t3t:"Uchtepa City assigned",t3d:"By resolution of the Cabinet of Ministers, the Uchtepa City project was assigned to the Olmazor Business City directorate.",
  t4t:"",t4d:"",
  map_google:"Google Maps",map_yandex:"Yandex Navigator",
  t5t:"Uchtepa City Launched",t5d:"Flagship project officially announced. Land documents formalised, design work started.",
  con_tag:"Contacts",con_title:"Get in Touch",
  con_lead:"For all investment questions, lot selection and negotiations — contact management directly.",
  role_dir:"Director",role_dep:"Deputy Director",ft_rights:"All rights reserved."
},
vi:{
  nav_ind:"Chỉ số",nav_lots:"Lô đất",nav_price:"Giá cả",nav_about:"Về chúng tôi",nav_contacts:"Liên hệ",
    proj3_tag:"Đang hoạt động · 2021",proj3_desc:"Khu công nghiệp hiện đại được thành lập theo sắc lệnh Tổng thống. Được Thủ tướng Uzbekistan và Thị trưởng Tashkent tin tưởng giao cho đội ngũ của chúng tôi.",
    t_yht:"Yangihayot Industrial Texnopark",t_yhd:"Theo sắc lệnh của Tổng thống, Khu công nghệ Yangihayot — khu công nghiệp hiện đại — được thành lập. Được Thủ tướng Uzbekistan và Thị trưởng Tashkent tin tưởng giao cho đội ngũ của chúng tôi.",
    nav_adv:"Lợi thế",
  adv_tag:"Tại sao Uchtepa City?",adv_title:"Lợi thế đầu tư",
  adv_lead:"Uchtepa City mang lại cho nhà đầu tư những lợi thế chiến lược và pháp lý độc đáo.",
  adv1_t:"Hạ tầng kỹ thuật đến ranh giới đỏ của nhà đầu tư",adv1_d:"Tất cả tiện ích (nước, gas, điện, thoát nước) được cung cấp đến ranh giới đỏ của nhà đầu tư miễn phí.",
  adv2_t:"Hỗ trợ toàn diện từ chính phủ",adv2_d:"Dự án được bảo đảm bởi nghị quyết của Hội đồng Bộ trưởng Uzbekistan. Bảo vệ pháp lý đầy đủ và bảo đảm nhà nước.",
  adv3_t:"Quyền xây dựng tòa nhà trên 30 tầng",adv3_d:"Uchtepa City là một trong số ít dự án ở Tashkent được phép xây dựng tòa nhà trên 30 tầng. FAR = 4.",
  adv4_t:"Ban Giám đốc thực hiện phá dỡ",adv4_d:"Việc phá dỡ các công trình do Ban Giám đốc thực hiện. Nhà đầu tư không phải chịu gánh nặng này.",
  adv5_t:"3 ha đất trống — có thể xây dựng ngay",adv5_d:"Hiện có 3 ha đất trống — có thể bắt đầu xây dựng ngay mà không cần chờ phá dỡ.",
  adv6_t:"Đất lân cận $1.100/m² — của chúng tôi $600/m²",adv6_d:"Các lô đất lân cận có giấy tờ đầy đủ cách 1.4 km có giá $1.100/m². Giá trung bình của chúng tôi — <strong>$600/m²</strong>.",
  adv7_t:"1,81 km bờ kênh Bozsuv",adv7_d:"Dự án trải dài 1,81 km dọc bờ kênh Bozsuv. Trong điều kiện nắng nóng, các dự án ven nước đặc biệt triển vọng.",
  adv8_t:"Một trong những quận xanh nhất Tashkent",adv8_d:"Quận Uchtepa là một trong những khu vực sinh thái nhất Tashkent với nhiều cây xanh, công viên và vườn.",
  adv9_t:"Vị trí chiến lược",
  loc1:"Đường vành đai nhỏ",loc1d:"Ngay cạnh",loc2:"Tashkent City",loc3:"Sân bay quốc tế",loc4:"Ga trung tâm",loc5:"Tàu điện ngầm",loc6:"Lô đất lân cận (có giấy tờ)",
    nav_faq:"Hỏi-Đáp",
  faq_tag:"Trả lời các câu hỏi chính",faq_title:"Về dự án",
  faq_lead:"Các câu trả lời dựa trên khung pháp lý hiện hành của Cộng hòa Uzbekistan.",
  faq1_t:"Chi phí giải phóng mặt bằng và tiến độ",faq1_d:"Tổng chi phí giải phóng mặt bằng — <strong>$145.7M</strong>. Thời gian dự kiến — 9–12 tháng.",faq1_l:"Cơ sở pháp lý: NQ №414 — 10 tháng 7 năm 2024",
  faq2_t:"Cơ chế hoàn trả chi phí nhà đầu tư",faq2_d:"Thủ tục hoàn trả chi phí ứng trước sẽ được điều chỉnh thông qua hợp đồng vay riêng biệt.",faq2_l:"Cơ sở pháp lý: NQ №461 — 5 tháng 6 năm 2019 (điều 30)",
  faq3_t:"Công viên ven sông và ranh giới dự án",faq3_d:"Vùng ven sông được đưa vào ranh giới dự án. Đại lộ xanh dọc kênh Bozsuv.",faq3_l:"Cơ sở pháp lý: NQ №414 — dọc kênh Bozsuv và phố Foziltepa",
  faq4_t:"Hệ số sử dụng đất (FAR)",faq4_d:"<strong>FAR = 4</strong>, trung bình 33 tầng, tổng diện tích xây dựng khoảng <strong>1.1 triệu m²</strong>.",faq4_l:"Cơ sở pháp lý: NQ №83 — 28 tháng 2 năm 2026",
  faq5_t:"Thành phần lãnh thổ dự án",faq5_note:"* Quy hoạch tổng thể được phát triển bởi ROX Group",
  ft1:"Tổng diện tích",ft2:"Diện tích xây dựng",ft3:"Bồi thường và phá dỡ (do nhà đầu tư)",ft4:"Bãi đỗ xe y tế",ft5:"Khu xanh và đường",ft5v:"Đang xác nhận",ft6:"Tổng số tiền bồi thường",
    nav_fut:"Tương lai",
  fut_tag:"Uchtepa City — Tương lai",fut_title:"Tương lai của dự án",fut_lead:"Hãy hình dung Uchtepa City sẽ trông như thế nào — qua video và hình ảnh trực quan.",
  t1t:"Thành lập công ty",t1d:"Năm 2018 chúng tôi bắt đầu hoạt động với dự án Olmazor Business City.",
    nav_proj:"Dự án",
  proj_tag:"Dự án đã hoàn thành",proj_title:"Kinh nghiệm của chúng tôi",
  proj1_tag:"Hoàn thành · 2022",proj1_desc:"23 ha công trình xuống cấp bị phá dỡ. Trung tâm kinh doanh và khu dân cư hiện đại được xây dựng thay thế.",
  proj2_tag:"Hoàn thành · 2023",proj2_desc:"44.5 ha — một trong những dự án tái thiết lớn nhất ở Tashkent. Toàn bộ khu phố cũ được làm mới hoàn toàn.",
  lbl_before:"Trước",lbl_after:"Sau",
  hero_tag:"Dự án đầu tư • Tashkent, quận Uchtepa",
  hero_desc:"26 ha — 31 tòa nhà dân cư, 2 trung tâm kinh doanh, trường học, nhà trẻ và đại lộ xanh ven kênh Bozsuv.",
  hero_btn:"Xem chỉ số",
  kpi1:"Diện tích xây dựng",kpi2:"Bồi thường",kpi3:"Lãnh thổ dự án",
  ind_tag:"Chỉ số kỹ thuật - kinh tế tổng hợp",ind_title:"Chỉ số dự án",
  ind_lead:"Các chỉ số kỹ thuật và kinh tế dựa trên quy hoạch tổng thể Uchtepa City.",
  i1:"Tổng diện tích vùng lô",i2:"Tổng diện tích xây dựng",i3:"Tổng diện tích xanh",
  i4:"Số trung tâm kinh doanh",i5:"Diện tích trung tâm kinh doanh",i6:"Số tòa nhà dân cư",
  i7:"Số tầng nhà dân cư",i8:"Tổng diện tích sàn dân cư",i9:"Tổng số căn hộ",
  i10:"Dân số",i11:"Diện tích xây dựng trường học",i12:"Số tầng trường học",
  i13:"Tổng diện tích sàn trường học",i14:"Diện tích xây dựng nhà trẻ",i15:"Số tầng nhà trẻ",
  i16:"Tổng diện tích sàn nhà trẻ",i17:"Chỗ đỗ xe mặt đất",
  i18:"Tổng diện tích sàn bán lẻ",i19:"Chỗ đỗ xe ngầm",
  plan_cap:"Uchtepa City — Quy hoạch tổng thể",
  lots_tag:"Phân chia vùng thành các lô",lots_title:"15 lô riêng lẻ",
  lots_lead:"Tổng diện tích 19.4 ha. Mỗi lô có thể được đăng ký như tài sản riêng biệt.",
  th_n:"Lô",th_type:"Loại",th_area:"Diện tích",
  b_res:"Dân cư",b_biz:"Trung tâm KD",b_soc:"Trường học",b_mtm:"Nhà trẻ",b_park:"Bãi đỗ xe",
  func_tag:"Phân bổ chức năng các tòa nhà",func_title:"Khu chức năng",
  leg1_t:"Nhà dân cư",leg1_d:"31 tòa, 18–22 tầng. Tổng diện tích sàn 819.809,6 m². 6.664 căn hộ, 22.148 cư dân.",
  leg2_t:"Trung tâm kinh doanh",leg2_d:"2 trung tâm. Tổng diện tích 246.328,8 m². Văn phòng, thương mại và dịch vụ.",
  leg3_t:"Tòa nhà trường học",leg3_d:"Trường 4 tầng. Diện tích xây dựng 1.719,3 m², tổng diện tích sàn 6.877,2 m².",
  leg4_t:"Nhà trẻ (MTM)",leg4_d:"Nhà trẻ 2 tầng. Diện tích xây dựng 951,5 m², tổng diện tích sàn 1.903 m².",
  price_tag:"Giá cả",price_title:"Giá trị đầu tư",
  price_lead:"Giá cạnh tranh và điều khoản thanh toán linh hoạt — điều kiện thuận lợi nhất cho nhà đầu tư.",
  p1_type:"Toàn bộ dự án",p1_desc:"Giá đầy đủ cho 26 ha với tất cả các lô và cơ sở hạ tầng. Bao gồm bồi thường và phá dỡ.",
  p2_type:"Giá mỗi m² (TB)",p2_desc:"Giá trung bình mỗi mét vuông tùy theo vị trí và mục đích lô.",
  p3_type:"Lô tối thiểu №4 (E-auksion)",p3_desc:"Giá mỗi m² khi mua lô №4 qua E-auksion. Diện tích lô 5.871,2 m².",
  p_req:"Gửi yêu cầu →",p_ask:"Hỏi giá lô →",p_info:"Chi tiết hơn →",
  comp_title:"Giá trung bình của các chủ đầu tư lân cận (m² / $)",our_price:"Giá của chúng tôi",our_val:"$600 /m²",
  about_tag:"Về chúng tôi",about_title:"Kinh nghiệm <em>ban quản lý</em>",
  ab1:"Từ năm 2018, <strong>ban quản lý</strong> đã tích lũy kinh nghiệm thực tế trong việc thu hút nhà đầu tư, giải phóng mặt bằng, chuẩn bị hạ tầng kỹ thuật và các lô đất cho những dự án đô thị lớn.",
  ab2:"Kinh nghiệm từ Olmazor Business City và Yunusobod Business City hiện được áp dụng trong quá trình chuẩn bị <strong>Uchtepa City</strong> cho nhà đầu tư.",
  ab3:"Bạn có thể xem vị trí Uchtepa City trên bản đồ:",
  t1t:"Thành lập ban quản lý",t1d:"Công việc với Olmazor Business City bắt đầu: tìm được nhà đầu tư, giải phóng mặt bằng và phân bổ khu đất cho nhà đầu tư. Do COVID-19 và giãn cách, việc giải phóng hoàn toàn kéo dài đến năm 2021; xây dựng hoàn thành năm 2023.",
  t2t:"Yunusobod Business City",t2d:"Một ban quản lý mới được thành lập nhưng đội ngũ chính vẫn được giữ lại. Nhà đầu tư được thu hút; khu đất dành cho nhà đầu tư được giải phóng đến năm 2022, đến năm 2023 khoảng 70-75% diện tích đã được chuẩn bị và giai đoạn tiếp theo được bàn giao cho đội ngũ khác.",
  t3t:"Uchtepa City được giao",t3d:"Theo nghị quyết của Nội các Bộ trưởng, dự án Uchtepa City được giao cho ban quản lý Olmazor Business City.",
  t4t:"",t4d:"",
  map_google:"Google Maps",map_yandex:"Yandex Navigator",
  t5t:"Khởi động Uchtepa City",t5d:"Dự án chính thức được công bố. Hoàn thiện hồ sơ đất, bắt đầu thiết kế.",
  con_tag:"Liên hệ",con_title:"Liên hệ với chúng tôi",
  con_lead:"Mọi câu hỏi về đầu tư, chọn lô và đàm phán — hãy liên hệ trực tiếp với ban lãnh đạo.",
  role_dir:"Giám đốc",role_dep:"Phó giám đốc",ft_rights:"Bảo lưu mọi quyền."
}
};

let currentLang='uz';
function setLang(lang){
  currentLang=lang;
  document.querySelectorAll('.lb').forEach(b=>b.classList.toggle('active',b.textContent.toLowerCase()===lang));
  const t=T[lang];
  document.querySelectorAll('[data-i]').forEach(el=>{
    const k=el.getAttribute('data-i');
    if(t[k]!==undefined) el.innerHTML=t[k];
  });
}
